const labels = {
  en: {
    yourName: 'Your Name',
    professionalSummary: 'Professional Summary',
    experience: 'Experience',
    education: 'Education',
    skills: 'Skills',
    projects: 'Projects',
    certifications: 'Certifications',
    languages: 'Languages',
    gpa: 'GPA',
    technologies: 'Technologies',
    link: 'Link',
    professionalProfile: 'Professional Profile',
    professionalExperience: 'Professional Experience',
    publications: 'Publications',
    researchProjects: 'Research Projects',
    teachingExperience: 'Teaching Experience',
    certificationsAwards: 'Certifications & Awards',
    thesis: 'Thesis',
    advisor: 'Advisor',
  },
  th: {
    yourName: 'ชื่อ-นามสกุล',
    professionalSummary: 'ประวัติโดยย่อ',
    experience: 'ประสบการณ์ทำงาน',
    education: 'การศึกษา',
    skills: 'ทักษะ',
    projects: 'ผลงานและโครงการ',
    certifications: 'ใบรับรอง',
    languages: 'ภาษา',
    gpa: 'เกรดเฉลี่ย',
    technologies: 'เทคโนโลยี',
    link: 'ลิงก์',
    professionalProfile: 'ประวัติและความเชี่ยวชาญ',
    professionalExperience: 'ประสบการณ์วิชาชีพ',
    publications: 'ผลงานตีพิมพ์',
    researchProjects: 'โครงการวิจัย',
    teachingExperience: 'ประสบการณ์การสอน',
    certificationsAwards: 'ใบรับรองและรางวัล',
    thesis: 'วิทยานิพนธ์',
    advisor: 'อาจารย์ที่ปรึกษา',
  },
};

export const getDocumentLabels = (language = 'en') => labels[language === 'th' ? 'th' : 'en'];
